# Header
menu:
  - title: Home
    url: /
    icon: home
  - title: Archives
    url: /test/archives
    icon: archive
  - title: About
    url: /about
    icon: info

rss: /atom.xml

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics:
favicon: 
twitter:

#cover: img/bg6.jpg
cover: 
slogan: "dont count the days, make the days count"